---
    - name: create symlink for to volume
      file:
        force: yes
        src: /volumes/docker
        path: /var/lib/docker
        state: link

    - name: Include OS-specific variables.
      include_vars: "{{ ansible_os_family }}.yml"
      when: ansible_distribution == 'RedHat'

    - name: Define java_packages.
      set_fact:
         java_packages: "{{ __java_packages | list }}"
      when: java_packages is not defined

    - name: install java
      yum:
         name: java-1.8.0
         state: present
      become: true

    - name: install java openkjdk
      yum:
         name: java-1.8.0-openjdk-devel
         state: present
      become: true

    - include: setup-RedHat.yml

# Environment setup.
    - name: Set JAVA_HOME if configured.
      template:
        src: java_home.sh.j2
        dest: /etc/profile.d/java_home.sh
        mode: 0644
      when: java_home is defined and java_home != ''
